### ISSUE TITLE
Add Github Action for building to a pages branch

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/3DTilesRendererJS#145]
Use the [add-and-commit](https://github.com/marketplace/actions/add-commit) action to build the example pages and push to a gh pages branch.

```yaml
name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Make Build
    - run: npm install
    - run: npm run build
    - name: Commit Build
      uses: EndBug/add-and-commit@v6
      with:
        author_name: Github Actions
        message: 'page build'
        branch: gh-pages
        add: 'example/bundle/*.js --force'
```
